// src/pages/ResetPassword.jsx
import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { LuLock } from 'react-icons/lu';

const ResetPassword = () => {
  // Grab the secure URL string token generated by crypto on the backend
  const { token } = useParams();
  const navigate = useNavigate();
  const API_BASE = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api';

  // Local State Management
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [loading, setLoading] = useState(false);

  // POST Execution: Commit the new credentials to the server layer
  const handleReset = async (e) => {
    e.preventDefault();

    // 1. Client-side match validation
    if (password !== confirmPassword) {
      return toast.error('Passwords do not match. Please re-verify.');
    }

    // 2. Minimum length safety guardrail
    if (password.length < 6) {
      return toast.error('Password must be at least 6 characters long.');
    }

    setLoading(true);

    try {
      const response = await fetch(`${API_BASE}/auth/reset-password/${token}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ password }),
      });

      const data = await response.json();

      if (data.success) {
        toast.success('Password updated successfully! Redirecting to login...');
        
        // Clear inputs immediately
        setPassword('');
        setConfirmPassword('');

        // Smooth transition back to login screen
        setTimeout(() => {
          navigate('/admin-login');
        }, 3000);
      } else {
        toast.error(data.message || 'Token has expired or is invalid.');
      }
    } catch (err) {
      toast.error('Network failure connecting to authentication cluster services.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-[calc(100vh-64px)] bg-slate-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8 font-sans antialiased">
      <div className="sm:mx-auto w-full sm:max-w-md">
        
        {/* Main Content Card Container */}
        <div className="bg-white py-8 px-6 shadow-xl border border-slate-200/60 rounded-xl sm:px-10">
          
          <div className="mb-6 text-center">
            <h2 className="text-xl font-bold text-[#0b1b3d] tracking-wide">
              Create New Password
            </h2>
            <p className="text-xs text-slate-400 mt-1.5 font-medium tracking-wide uppercase">
              Update Administrative Credentials
            </p>
          </div>

          <form className="space-y-5" onSubmit={handleReset}>
            
            {/* New Password Field */}
            <div>
              <label className="block text-xs font-semibold text-slate-600 uppercase tracking-wider mb-2">
                New Password
              </label>
              <div className="relative rounded-md shadow-sm">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                  <LuLock className="text-sm" />
                </div>
                <input
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="block w-full pl-9 pr-3 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500 focus:bg-white transition-all"
                  placeholder="••••••••"
                  required
                  disabled={loading}
                />
              </div>
            </div>

            {/* Confirm Password Field */}
            <div>
              <label className="block text-xs font-semibold text-slate-600 uppercase tracking-wider mb-2">
                Confirm New Password
              </label>
              <div className="relative rounded-md shadow-sm">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                  <LuLock className="text-sm" />
                </div>
                <input
                  type="password"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  className="block w-full pl-9 pr-3 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500 focus:bg-white transition-all"
                  placeholder="••••••••"
                  required
                  disabled={loading}
                />
              </div>
            </div>

            {/* Form Submit Button */}
            <div className="pt-2">
              <button
                type="submit"
                disabled={loading}
                className="w-full flex justify-center py-2.5 px-4 border border-transparent rounded-lg shadow-md text-sm font-semibold text-white bg-[#0b1b3d] hover:bg-[#112754] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#0b1b3d] disabled:opacity-50 transition-all cursor-pointer tracking-wide"
              >
                {loading ? 'Updating Credentials...' : 'Save New Password'}
              </button>
            </div>

          </form>
        </div>
      </div>
    </div>
  );
};

export default ResetPassword;